// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzkqigzzaibwnvausxeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6a3FpZ3p6YWlid252YXVzeGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTMyOTEsImV4cCI6MjA3NDE2OTI5MX0.je90jLj45JRH4qxcSq9v_HjD29CYlOUNW97sTxQGpXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});